/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fiberhome.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-11-20")
public class ProcStatus implements org.apache.thrift.TBase<ProcStatus, ProcStatus._Fields>, java.io.Serializable, Cloneable, Comparable<ProcStatus> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProcStatus");

  private static final org.apache.thrift.protocol.TField PROC_CPU_FIELD_DESC = new org.apache.thrift.protocol.TField("ProcCPU", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField MEMORY_COST_FIELD_DESC = new org.apache.thrift.protocol.TField("MemoryCost", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("Path", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ProcStatusStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ProcStatusTupleSchemeFactory();

  public double ProcCPU; // required
  public double MemoryCost; // required
  public java.lang.String Path; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROC_CPU((short)1, "ProcCPU"),
    MEMORY_COST((short)2, "MemoryCost"),
    PATH((short)3, "Path");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROC_CPU
          return PROC_CPU;
        case 2: // MEMORY_COST
          return MEMORY_COST;
        case 3: // PATH
          return PATH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROCCPU_ISSET_ID = 0;
  private static final int __MEMORYCOST_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROC_CPU, new org.apache.thrift.meta_data.FieldMetaData("ProcCPU", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.MEMORY_COST, new org.apache.thrift.meta_data.FieldMetaData("MemoryCost", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.PATH, new org.apache.thrift.meta_data.FieldMetaData("Path", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProcStatus.class, metaDataMap);
  }

  public ProcStatus() {
  }

  public ProcStatus(
    double ProcCPU,
    double MemoryCost,
    java.lang.String Path)
  {
    this();
    this.ProcCPU = ProcCPU;
    setProcCPUIsSet(true);
    this.MemoryCost = MemoryCost;
    setMemoryCostIsSet(true);
    this.Path = Path;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProcStatus(ProcStatus other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ProcCPU = other.ProcCPU;
    this.MemoryCost = other.MemoryCost;
    if (other.isSetPath()) {
      this.Path = other.Path;
    }
  }

  public ProcStatus deepCopy() {
    return new ProcStatus(this);
  }

  @Override
  public void clear() {
    setProcCPUIsSet(false);
    this.ProcCPU = 0.0;
    setMemoryCostIsSet(false);
    this.MemoryCost = 0.0;
    this.Path = null;
  }

  public double getProcCPU() {
    return this.ProcCPU;
  }

  public ProcStatus setProcCPU(double ProcCPU) {
    this.ProcCPU = ProcCPU;
    setProcCPUIsSet(true);
    return this;
  }

  public void unsetProcCPU() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PROCCPU_ISSET_ID);
  }

  /** Returns true if field ProcCPU is set (has been assigned a value) and false otherwise */
  public boolean isSetProcCPU() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PROCCPU_ISSET_ID);
  }

  public void setProcCPUIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PROCCPU_ISSET_ID, value);
  }

  public double getMemoryCost() {
    return this.MemoryCost;
  }

  public ProcStatus setMemoryCost(double MemoryCost) {
    this.MemoryCost = MemoryCost;
    setMemoryCostIsSet(true);
    return this;
  }

  public void unsetMemoryCost() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MEMORYCOST_ISSET_ID);
  }

  /** Returns true if field MemoryCost is set (has been assigned a value) and false otherwise */
  public boolean isSetMemoryCost() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MEMORYCOST_ISSET_ID);
  }

  public void setMemoryCostIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MEMORYCOST_ISSET_ID, value);
  }

  public java.lang.String getPath() {
    return this.Path;
  }

  public ProcStatus setPath(java.lang.String Path) {
    this.Path = Path;
    return this;
  }

  public void unsetPath() {
    this.Path = null;
  }

  /** Returns true if field Path is set (has been assigned a value) and false otherwise */
  public boolean isSetPath() {
    return this.Path != null;
  }

  public void setPathIsSet(boolean value) {
    if (!value) {
      this.Path = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PROC_CPU:
      if (value == null) {
        unsetProcCPU();
      } else {
        setProcCPU((java.lang.Double)value);
      }
      break;

    case MEMORY_COST:
      if (value == null) {
        unsetMemoryCost();
      } else {
        setMemoryCost((java.lang.Double)value);
      }
      break;

    case PATH:
      if (value == null) {
        unsetPath();
      } else {
        setPath((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PROC_CPU:
      return getProcCPU();

    case MEMORY_COST:
      return getMemoryCost();

    case PATH:
      return getPath();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PROC_CPU:
      return isSetProcCPU();
    case MEMORY_COST:
      return isSetMemoryCost();
    case PATH:
      return isSetPath();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ProcStatus)
      return this.equals((ProcStatus)that);
    return false;
  }

  public boolean equals(ProcStatus that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ProcCPU = true;
    boolean that_present_ProcCPU = true;
    if (this_present_ProcCPU || that_present_ProcCPU) {
      if (!(this_present_ProcCPU && that_present_ProcCPU))
        return false;
      if (this.ProcCPU != that.ProcCPU)
        return false;
    }

    boolean this_present_MemoryCost = true;
    boolean that_present_MemoryCost = true;
    if (this_present_MemoryCost || that_present_MemoryCost) {
      if (!(this_present_MemoryCost && that_present_MemoryCost))
        return false;
      if (this.MemoryCost != that.MemoryCost)
        return false;
    }

    boolean this_present_Path = true && this.isSetPath();
    boolean that_present_Path = true && that.isSetPath();
    if (this_present_Path || that_present_Path) {
      if (!(this_present_Path && that_present_Path))
        return false;
      if (!this.Path.equals(that.Path))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(ProcCPU);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(MemoryCost);

    hashCode = hashCode * 8191 + ((isSetPath()) ? 131071 : 524287);
    if (isSetPath())
      hashCode = hashCode * 8191 + Path.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ProcStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetProcCPU()).compareTo(other.isSetProcCPU());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcCPU()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ProcCPU, other.ProcCPU);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMemoryCost()).compareTo(other.isSetMemoryCost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMemoryCost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.MemoryCost, other.MemoryCost);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPath()).compareTo(other.isSetPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Path, other.Path);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ProcStatus(");
    boolean first = true;

    sb.append("ProcCPU:");
    sb.append(this.ProcCPU);
    first = false;
    if (!first) sb.append(", ");
    sb.append("MemoryCost:");
    sb.append(this.MemoryCost);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Path:");
    if (this.Path == null) {
      sb.append("null");
    } else {
      sb.append(this.Path);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProcStatusStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProcStatusStandardScheme getScheme() {
      return new ProcStatusStandardScheme();
    }
  }

  private static class ProcStatusStandardScheme extends org.apache.thrift.scheme.StandardScheme<ProcStatus> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProcStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROC_CPU
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.ProcCPU = iprot.readDouble();
              struct.setProcCPUIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MEMORY_COST
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.MemoryCost = iprot.readDouble();
              struct.setMemoryCostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Path = iprot.readString();
              struct.setPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProcStatus struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PROC_CPU_FIELD_DESC);
      oprot.writeDouble(struct.ProcCPU);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MEMORY_COST_FIELD_DESC);
      oprot.writeDouble(struct.MemoryCost);
      oprot.writeFieldEnd();
      if (struct.Path != null) {
        oprot.writeFieldBegin(PATH_FIELD_DESC);
        oprot.writeString(struct.Path);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProcStatusTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProcStatusTupleScheme getScheme() {
      return new ProcStatusTupleScheme();
    }
  }

  private static class ProcStatusTupleScheme extends org.apache.thrift.scheme.TupleScheme<ProcStatus> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProcStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProcCPU()) {
        optionals.set(0);
      }
      if (struct.isSetMemoryCost()) {
        optionals.set(1);
      }
      if (struct.isSetPath()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetProcCPU()) {
        oprot.writeDouble(struct.ProcCPU);
      }
      if (struct.isSetMemoryCost()) {
        oprot.writeDouble(struct.MemoryCost);
      }
      if (struct.isSetPath()) {
        oprot.writeString(struct.Path);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProcStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.ProcCPU = iprot.readDouble();
        struct.setProcCPUIsSet(true);
      }
      if (incoming.get(1)) {
        struct.MemoryCost = iprot.readDouble();
        struct.setMemoryCostIsSet(true);
      }
      if (incoming.get(2)) {
        struct.Path = iprot.readString();
        struct.setPathIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

