/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fiberhome.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ResourceEnum implements org.apache.thrift.TEnum {
  None(0),
  Board(1),
  NE(2),
  Topology(4),
  Port(8);

  private final int value;

  private ResourceEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResourceEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return None;
      case 1:
        return Board;
      case 2:
        return NE;
      case 4:
        return Topology;
      case 8:
        return Port;
      default:
        return null;
    }
  }
}
