/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fiberhome.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-11-20")
public class RPCApplicationException extends org.apache.thrift.TException implements org.apache.thrift.TBase<RPCApplicationException, RPCApplicationException._Fields>, java.io.Serializable, Cloneable, Comparable<RPCApplicationException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RPCApplicationException");

  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("Message", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RPCSTACK_TRACE_FIELD_DESC = new org.apache.thrift.protocol.TField("RPCStackTrace", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ERROR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("ErrorCode", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RPCApplicationExceptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RPCApplicationExceptionTupleSchemeFactory();

  public java.lang.String Message; // required
  public java.lang.String RPCStackTrace; // required
  public int ErrorCode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE((short)1, "Message"),
    RPCSTACK_TRACE((short)2, "RPCStackTrace"),
    ERROR_CODE((short)3, "ErrorCode");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE
          return MESSAGE;
        case 2: // RPCSTACK_TRACE
          return RPCSTACK_TRACE;
        case 3: // ERROR_CODE
          return ERROR_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ERRORCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("Message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RPCSTACK_TRACE, new org.apache.thrift.meta_data.FieldMetaData("RPCStackTrace", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR_CODE, new org.apache.thrift.meta_data.FieldMetaData("ErrorCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RPCApplicationException.class, metaDataMap);
  }

  public RPCApplicationException() {
  }

  public RPCApplicationException(
    java.lang.String Message,
    java.lang.String RPCStackTrace,
    int ErrorCode)
  {
    this();
    this.Message = Message;
    this.RPCStackTrace = RPCStackTrace;
    this.ErrorCode = ErrorCode;
    setErrorCodeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RPCApplicationException(RPCApplicationException other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessage()) {
      this.Message = other.Message;
    }
    if (other.isSetRPCStackTrace()) {
      this.RPCStackTrace = other.RPCStackTrace;
    }
    this.ErrorCode = other.ErrorCode;
  }

  public RPCApplicationException deepCopy() {
    return new RPCApplicationException(this);
  }

  @Override
  public void clear() {
    this.Message = null;
    this.RPCStackTrace = null;
    setErrorCodeIsSet(false);
    this.ErrorCode = 0;
  }

  public java.lang.String getMessage() {
    return this.Message;
  }

  public RPCApplicationException setMessage(java.lang.String Message) {
    this.Message = Message;
    return this;
  }

  public void unsetMessage() {
    this.Message = null;
  }

  /** Returns true if field Message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.Message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.Message = null;
    }
  }

  public java.lang.String getRPCStackTrace() {
    return this.RPCStackTrace;
  }

  public RPCApplicationException setRPCStackTrace(java.lang.String RPCStackTrace) {
    this.RPCStackTrace = RPCStackTrace;
    return this;
  }

  public void unsetRPCStackTrace() {
    this.RPCStackTrace = null;
  }

  /** Returns true if field RPCStackTrace is set (has been assigned a value) and false otherwise */
  public boolean isSetRPCStackTrace() {
    return this.RPCStackTrace != null;
  }

  public void setRPCStackTraceIsSet(boolean value) {
    if (!value) {
      this.RPCStackTrace = null;
    }
  }

  public int getErrorCode() {
    return this.ErrorCode;
  }

  public RPCApplicationException setErrorCode(int ErrorCode) {
    this.ErrorCode = ErrorCode;
    setErrorCodeIsSet(true);
    return this;
  }

  public void unsetErrorCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  /** Returns true if field ErrorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ERRORCODE_ISSET_ID);
  }

  public void setErrorCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ERRORCODE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case RPCSTACK_TRACE:
      if (value == null) {
        unsetRPCStackTrace();
      } else {
        setRPCStackTrace((java.lang.String)value);
      }
      break;

    case ERROR_CODE:
      if (value == null) {
        unsetErrorCode();
      } else {
        setErrorCode((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE:
      return getMessage();

    case RPCSTACK_TRACE:
      return getRPCStackTrace();

    case ERROR_CODE:
      return getErrorCode();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE:
      return isSetMessage();
    case RPCSTACK_TRACE:
      return isSetRPCStackTrace();
    case ERROR_CODE:
      return isSetErrorCode();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RPCApplicationException)
      return this.equals((RPCApplicationException)that);
    return false;
  }

  public boolean equals(RPCApplicationException that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Message = true && this.isSetMessage();
    boolean that_present_Message = true && that.isSetMessage();
    if (this_present_Message || that_present_Message) {
      if (!(this_present_Message && that_present_Message))
        return false;
      if (!this.Message.equals(that.Message))
        return false;
    }

    boolean this_present_RPCStackTrace = true && this.isSetRPCStackTrace();
    boolean that_present_RPCStackTrace = true && that.isSetRPCStackTrace();
    if (this_present_RPCStackTrace || that_present_RPCStackTrace) {
      if (!(this_present_RPCStackTrace && that_present_RPCStackTrace))
        return false;
      if (!this.RPCStackTrace.equals(that.RPCStackTrace))
        return false;
    }

    boolean this_present_ErrorCode = true;
    boolean that_present_ErrorCode = true;
    if (this_present_ErrorCode || that_present_ErrorCode) {
      if (!(this_present_ErrorCode && that_present_ErrorCode))
        return false;
      if (this.ErrorCode != that.ErrorCode)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + Message.hashCode();

    hashCode = hashCode * 8191 + ((isSetRPCStackTrace()) ? 131071 : 524287);
    if (isSetRPCStackTrace())
      hashCode = hashCode * 8191 + RPCStackTrace.hashCode();

    hashCode = hashCode * 8191 + ErrorCode;

    return hashCode;
  }

  @Override
  public int compareTo(RPCApplicationException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Message, other.Message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRPCStackTrace()).compareTo(other.isSetRPCStackTrace());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRPCStackTrace()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.RPCStackTrace, other.RPCStackTrace);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetErrorCode()).compareTo(other.isSetErrorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ErrorCode, other.ErrorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RPCApplicationException(");
    boolean first = true;

    sb.append("Message:");
    if (this.Message == null) {
      sb.append("null");
    } else {
      sb.append(this.Message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("RPCStackTrace:");
    if (this.RPCStackTrace == null) {
      sb.append("null");
    } else {
      sb.append(this.RPCStackTrace);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ErrorCode:");
    sb.append(this.ErrorCode);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RPCApplicationExceptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RPCApplicationExceptionStandardScheme getScheme() {
      return new RPCApplicationExceptionStandardScheme();
    }
  }

  private static class RPCApplicationExceptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<RPCApplicationException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RPCApplicationException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RPCSTACK_TRACE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.RPCStackTrace = iprot.readString();
              struct.setRPCStackTraceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ERROR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ErrorCode = iprot.readI32();
              struct.setErrorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RPCApplicationException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.Message);
        oprot.writeFieldEnd();
      }
      if (struct.RPCStackTrace != null) {
        oprot.writeFieldBegin(RPCSTACK_TRACE_FIELD_DESC);
        oprot.writeString(struct.RPCStackTrace);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ERROR_CODE_FIELD_DESC);
      oprot.writeI32(struct.ErrorCode);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RPCApplicationExceptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RPCApplicationExceptionTupleScheme getScheme() {
      return new RPCApplicationExceptionTupleScheme();
    }
  }

  private static class RPCApplicationExceptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<RPCApplicationException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RPCApplicationException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMessage()) {
        optionals.set(0);
      }
      if (struct.isSetRPCStackTrace()) {
        optionals.set(1);
      }
      if (struct.isSetErrorCode()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetMessage()) {
        oprot.writeString(struct.Message);
      }
      if (struct.isSetRPCStackTrace()) {
        oprot.writeString(struct.RPCStackTrace);
      }
      if (struct.isSetErrorCode()) {
        oprot.writeI32(struct.ErrorCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RPCApplicationException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.Message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.RPCStackTrace = iprot.readString();
        struct.setRPCStackTraceIsSet(true);
      }
      if (incoming.get(2)) {
        struct.ErrorCode = iprot.readI32();
        struct.setErrorCodeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

